module.exports = [
  {'code': '82', 'name': '澳门', 'firstLetter': 'A'},
  {'code': '34', 'name': '安徽', 'firstLetter': ''},
  {'code': '11', 'name': '北京', 'firstLetter': 'B'},
  {'code': '50', 'name': '重庆', 'firstLetter': 'C'},
  {'code': '35', 'name': '福建', 'firstLetter': 'F'},
  {'code': '62', 'name': '甘肃', 'firstLetter': 'G'},
  {'code': '44', 'name': '广东', 'firstLetter': ''},
  {'code': '45', 'name': '广西', 'firstLetter': ''},
  {'code': '52', 'name': '贵州', 'firstLetter': ''},
  {'code': '46', 'name': '海南', 'firstLetter': 'H'},
  {'code': '13', 'name': '河北', 'firstLetter': ''},
  {'code': '41', 'name': '河南', 'firstLetter': ''},
  {'code': '23', 'name': '黑龙江', 'firstLetter': ''},
  {'code': '42', 'name': '湖北', 'firstLetter': ''},
  {'code': '43', 'name': '湖南', 'firstLetter': ''},
  {'code': '22', 'name': '吉林', 'firstLetter': 'J'},
  {'code': '32', 'name': '江苏', 'firstLetter': ''},
  {'code': '36', 'name': '江西', 'firstLetter': ''},
  {'code': '21', 'name': '辽宁', 'firstLetter': 'L'},
  {'code': '15', 'name': '内蒙古', 'firstLetter': 'N'},
  {'code': '64', 'name': '宁夏', 'firstLetter': ''},
  {'code': '63', 'name': '青海', 'firstLetter': 'Q'},
  {'code': '37', 'name': '山东', 'firstLetter': 'S'},
  {'code': '14', 'name': '山西', 'firstLetter': ''},
  {'code': '61', 'name': '陕西', 'firstLetter': ''},
  {'code': '31', 'name': '上海', 'firstLetter': ''},
  {'code': '51', 'name': '四川', 'firstLetter': ''},
  {'code': '71', 'name': '台湾', 'firstLetter': 'T'},
  {'code': '12', 'name': '天津', 'firstLetter': ''},
  {'code': '54', 'name': '西藏', 'firstLetter': 'X'},
  {'code': '81', 'name': '香港', 'firstLetter': ''},
  {'code': '65', 'name': '新疆', 'firstLetter': ''},
  {'code': '53', 'name': '云南', 'firstLetter': 'Y'},
  {'code': '33', 'name': '浙江', 'firstLetter': 'Z'}
]

